### ISSUE TITLE
Alertboxes don't show text

### ISSUE THREAD

**Issue by alphabernd** [LotarProject/dokuwiki-plugin-bootswrapper#1]
Hi,
alert boxes dont show normal text only snippets that have been marked in another way for example links or bold text.

![alert-src](https://cloud.githubusercontent.com/assets/3717732/7919651/09dd6c00-089a-11e5-835f-c1d4b0410275.png)
![alert-displayed](https://cloud.githubusercontent.com/assets/3717732/7919656/0e20389c-089a-11e5-82e1-eee70469d79c.png)

**Comment by HavocKKS** [comment]
Hello, I believe it is just a typo.

Found in **/syntax/alert.php**

```php
 list($state, $classes, $content, $attributes) = $data;
```

It sould be :

```php
 list($state, $content, $classes, $attributes) = $data;
```

What do you yhink ?

**Comment by alphabernd** [comment]
I made the change in the file and alertboxes work now as expected
