### ISSUE TITLE
Issue with parse page on a new version Dokuwiki - 2018-04-22a "Greebo"

### ISSUE THREAD

**Issue by VadimBalabin** [LotarProject/dokuwiki-plugin-bootswrapper#100]
Get error on a new version Dokuwiki - 2018-04-22a "Greebo", and page not parsed.
![image](https://user-images.githubusercontent.com/44360083/51036547-e028f800-15c6-11e9-9b9d-a8b9d731e02d.png)

More info and solution in [#2611](https://github.com/splitbrain/dokuwiki/issues/2611)

**Comment by phy25** [comment]
> In `plugins\bootswrapper\syntax\collumn.php` replace on correct regular expression:
>
> ```php
> public $pattern_start = '<col.*?>(?=.*?</col>)';
> ```
> changed
> ```php
> public $pattern_start = '<col\b.*?>(?=.*?</col>)';
> ```

https://github.com/splitbrain/dokuwiki/issues/2611#issuecomment-453516026

**Comment by LotarProject** [comment]
Fixed in dev branch.
Thanks to @phy25 for patch!

Stay tuned ;)
Joseph
