### ISSUE TITLE
Whicht Template needed?

### ISSUE THREAD

**Issue by dior1** [LotarProject/dokuwiki-plugin-bootswrapper#11]
Hi,

do I Need to use the Bootstrap 3 Template to use the Bootstrap Wrapper Plugin?
I´m using the 20Cones Template and the Bootstrap Plugin did not work.

Kind regards,
DIOR

**Comment by LotarProject** [comment]
Hi! At this moment this plugin work only with a Bootstrap-based template.

This plugin provide a configuration called "loadBootstrap", but i don't know the behavior with non-bootstrap template.

Best regards,
Joseph
