### ISSUE TITLE
TOC Menu appears under Carousel

### ISSUE THREAD

**Issue by stevenj** [LotarProject/dokuwiki-plugin-bootswrapper#12]
The TOC Menu, in the Bootstrap 3 theme, appears under the Carousel when expanded.  This makes it impossible to put a Carousel at the top of the page, or to use the TOC Menu with a Carousel at the top of a page.

In the image here, the red area is the Carousel.
![toc-under-carousel](https://cloud.githubusercontent.com/assets/764829/9594924/80e0a7c6-5094-11e5-844d-cfcfece79118.jpg)

**Comment by LotarProject** [comment]
Issue fixed in recent release of Bootstrap3 template.
