### ISSUE TITLE
Icons on buttons with external links

### ISSUE THREAD

**Issue by LotarProject** [LotarProject/dokuwiki-plugin-bootswrapper#14]
When creating a button with a external link it will add the globe icon even if you specify another icon.
I think the globe icon should be removed if another icon is specified for the button.
If this can't be done the globe icon should at least have the same color formatting as other icons because right now it looks really odd.
http://i.imgur.com/tmu1z3g.png

(see @worstboy32 issue LotarProject/dokuwiki-template-bootstrap3#82)

**Comment by worstboy32** [comment]
<3 thanks
