### ISSUE TITLE
Icon in Panel

### ISSUE THREAD

**Issue by baew** [LotarProject/dokuwiki-plugin-bootswrapper#15]
Icon in Panel don't work!

**Comment by LotarProject** [comment]
Hi! You have a snippet of code ?

Best regards,
Joseph

**Comment by baew** [comment]
If i use
```
<panel type="default" title="Title of Panel" subtitle="Subtitle" icon="fa fa-house">
Panel content
</panel>
```

I can't see an icon 

```
If i use
  <panel type="default" title="Title of Panel" subtitle="Subtitle" icon="fa fa-house fa-fw">
  Panel content
  </panel>
```

I can see it.

Best regards,
Bastian

**Comment by LotarProject** [comment]
Hi! I have tested in my local Wiki and changed the icon from ``fa-house`` to ``fa-home`` and i see the icons.

This behavior occur with other icons ?

Best regards,
Joseph
