### ISSUE TITLE
Collapse button in sidebar do not work properly

### ISSUE THREAD

**Issue by Shadoward** [LotarProject/dokuwiki-plugin-bootswrapper#16]
Hi,

Collapse button in sidebar page do not work properly.
The button is always collapse. (option true or false selected).
Is working fine in normal page.

Thanks

<button collapse="foo">Click Me</button>
<collapse id="foo" collapsed="true">
</collapse>

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue.
Please send me a snippet of code to test in my dev environment.

Best regards
Joseph

**Comment by Shadoward** [comment]
Hi,

You can find the code here:
https://gist.github.com/Shadoward/378d1bf949fcda51d066#file-sidebar

Thanks,

**Comment by Shadoward** [comment]
Thanks
