### ISSUE TITLE
Nav Tabs/Pills do not work correctly

### ISSUE THREAD

**Issue by Shadoward** [LotarProject/dokuwiki-plugin-bootswrapper#17]
Hi,

When using the Nav Tabs or Pills, the dropdown do not appear correctly.
If is located in the PageHeader (tabs) for example nothing appear. 
In the sidebar (pills) the first pills have two options appearing in the dropdown menu, the second just one option and last one none.
The navbar on the top of the wiki is working fine.

I think is a problem with the size o the windows dropdowns.

Thanks,

<nav type="tabs">
- DokuWiki
  - 1
  - 2
  - 3
- DokuWiki
  - 1
  - 2
  - 3
- DokuWiki
  - 1
  - 2
  - 3
    </nav>

**Comment by Digitalin** [comment]
Hi, 
I have the same issue, using include for an internal navbar in private namespaces 

    ~~NOTOC~~
    <nav type="pills" justified="true">
    {{page>foo:bar:orga&inline&nobutton&nouser&nodate}}
    </nav>
I have tried with tabs and pills, same result. It works well with a simple menu but not with sub-menu, as explained above. 
But it does work well with 

    <nav type="pills" stacked="true">

which is nice but not so suitable. 
Could be nice to have this feature working well. A  nice way to get a quick access to pages. 
What part of code would be useful for debugging ?

Thanks.

**Comment by Digitalin** [comment]
Hi, 

Happy to see it works fine now :+1: 

```
<nav type="pills" justified="true">
  * [[foo:equipes:accueil|Accueil]]
  * Administration
    * [[foo:equipes:admin|Administration]]
    * [[foo:equipes:archives|Archives]]
    * [[foo:equipes:catalog|Catalogue]]
  * Numérique 
    * ...
</nav>
```

Thanks.
