### ISSUE TITLE
Panel and Pane

### ISSUE THREAD

**Issue by GenesisFrog** [LotarProject/dokuwiki-plugin-bootswrapper#22]
I had to change this line in pane.php in order to work with Panels and Panes on the same page:

`protected $pattern_start  = '<pane.*?>(?=.*?</pane>)';`

to

`protected $pattern_start  = '<pane .*?>(?=.*?</pane>)';`

Note the space between pane and .*?

**Comment by Rojoss** [comment]
Oh was about to report this bug as I just encountered the same issue but guess it's not needed anymore. :) Thanks for that code btw got it fixed for now at least.

**Comment by LotarProject** [comment]
Fixed in latest release v2017-03-21
