### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-plugin-bootswrapper#23]
Hello, 

I have a bug with the last update on Detritus. A message says it is updated but a warn is still telling to update the plugin :
    Payer un café à l'auteur !
URL de téléchargement :
    github.com/LotarProject/dokuwik…wrapper/zipball/master
Entrepôt :
    github.com/LotarProject/dokuwiki-plugin-bootswrapper/
Version installée :
    2016-01-18
Votre dernière mise à jour :
    Sat, 13 Feb 2016 11:30:48 +0100
Version disponible :
    2016-02-11
Fournit :
    Action, Syntax
Compatible avec :
    "Detritus" (2015-08-10), "Hrun" (2014-09-29), "Weatherwax" (2013-05-10)
Similaire à :
    :wrap

Thanks.

**Comment by Soeldner** [comment]
Hi,

The same here. the update is ok but still old version.

![screenshot at 2016-02-13 15 39 29](https://cloud.githubusercontent.com/assets/1868211/13028209/a47662e2-d268-11e5-83c1-8af7ab616217.jpg)

timestamp of files

![screenshot at 2016-02-13 15 40 15](https://cloud.githubusercontent.com/assets/1868211/13028210/a478b6dc-d268-11e5-87f0-1cbf9197cfbf.jpg)

**Comment by LotarProject** [comment]
Sorry, the push in GitHub was not successful. Can you retry now ?

At your disposal,
Joseph

**Comment by Digitalin** [comment]
Hi Joseph, 

It works fine now. Thanks.

All the best.

**Comment by Soeldner** [comment]
works :) thx

**Comment by LotarProject** [comment]
;)
