### ISSUE TITLE
(Accordion) Option to make panel header clickable instead of just the title.

### ISSUE THREAD

**Issue by Rojoss** [LotarProject/dokuwiki-plugin-bootswrapper#25]
Every time I update I have to manually change this again because I find it pretty annoying that you can only click the title of the panel and not the entire heading of the panel.
I can see why it's default but it would be great if you could add a simple option for it.

Inside `Scripts.js` on line `212` at accordion.

``` php
$panel.find('h4.panel-title').wrapInner('<a role="button" data-toggle="collapse" data-parent="#'+ accordion_id +'" href="#'+ panel_id +'">');
```

Instead I put this:

``` php
$panel.find('.panel-heading').wrap('<a role="button" data-toggle="collapse" data-parent="#'+ accordion_id +'" href="#'+ panel_id +'">');
```

If you could suround that with an option it would be great so I don't have to manually change it every time. <3

**Comment by LotarProject** [comment]
Hi! Thanks to your suggests.

Best regards,
Joseph

**Comment by Rojoss** [comment]
Thanks for doing this! :)
