### ISSUE TITLE
Default text color in Text syntax

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-plugin-bootswrapper#26]
When aligning text the "text-muted color" is automatically used.
I've changed the following in "syntax\text.php".

Type , default to "null" (instead of muted)
Align, default to "left" (instead of null)

Would be nice to change with these new values in the next version of the file.
What do you think ?

**Comment by LotarProject** [comment]
Hi! Thanks for your suggests!

Best regards,
Joseph!
