### ISSUE TITLE
Table of Contents Highlighting

### ISSUE THREAD

**Issue by mholttech** [LotarProject/dokuwiki-plugin-bootswrapper#39]
No matter what i do the "Active" link on the TOC isn't changing, am I missing something or is this a bug?

![2016-03-16 10_04_59-environments_virtual_secure1 it bible](https://cloud.githubusercontent.com/assets/6945933/13821394/a77e9c66-eb5e-11e5-9cd7-f570c0ffd58e.png)

**Comment by polyzen** [comment]
I believe I've seen this happen when the third heading is in view when you're at the top of the page.
