### ISSUE TITLE
bootswrapper desactivate showTools menu

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-plugin-bootswrapper#4]
Hi, 

I have installed Bootstrap3 that works fine, then installed Bootswrapper and enabled it in the config manager (load bootswrapper). After that, impossible to open the Show tools menu and the show themes switcher as well. Have to : ?do=admin in the address bar to get the admin config. 
I can repeat each time. I tried to remove and reinstall the plugin but same issue. 
A message says : " La version 2015-04-20 est disponible. " but impossible to really update.  The plugin.info.txt : date 2015-04-12
Any idea ? 
Thanks.

**Comment by LotarProject** [comment]
Hi! If you have the Bootstrap3 template you don't enable the plugin in Config Manager. This flag is used only for the people who don't have a Bootstrap based template.

I have added in my last commit a brief message to explain the flag.

Thanks for reporting this issue ;)

Best regards,
Joseph

**Comment by Digitalin** [comment]
Thanks you to pay attention :-)
It is not really a bug, more a problem between chair and keyboard.
By default, the value is 0, as  explained at https://www.dokuwiki.org/plugin:bootswrapper#configuration_and_settings

Cheers, 
Digitalin.
