### ISSUE TITLE
Support for icons in tab pane

### ISSUE THREAD

**Issue by AlekSet** [LotarProject/dokuwiki-plugin-bootswrapper#41]
Hi.
Support for icons in tab pane will be great.
It does not matter whether, in tab title or in attribute.

**Comment by LotarProject** [comment]
Hi Alek! Can you add an icon in tab/nav using Icons plugin like the ``:navbar`` hook in Bootstrap3 Template:

```
<tabs>
  * {{fa>home}} DokuWiki
    * [[wiki:welcome]]
    * [[wiki:syntax]]
</tabs>
```

**Comment by AlekSet** [comment]
Sometimes the hardest to come up with simple solutions ;-)

**Comment by LotarProject** [comment]
Hi! I have added some examples in http://lotar.altervista.org/dokuwiki/wiki/plugin/bootswrapper/nav#with_icons_plugin
