### ISSUE TITLE
Images dont load correctly

### ISSUE THREAD

**Issue by gldtn** [LotarProject/dokuwiki-plugin-bootswrapper#44]
I've being try to figure out why my thumbnails won't randomly load on a page. If I have only 4 images, it works fine, anything past the 4th the images would randomly not load on the page. Not sure if this is related to the bootstrap plugin or it's a issue from dokuwiki itself or if it's just something on my side.

You can take a peek here: https://wiki.teonanacatl.org/informacoes_basicas/indice 

Can someone try to reproduce. I believe you can view the source code on my wiki! If you refresh the page several times you'll see what I mean.

Thanks!

**Comment by AlekSet** [comment]
It has nothing to do with bootstrap 3. You made just a little mistake. U have link to _thumb_05.jpg_, but there is no _thumb_05.jpg_ file. There is _thumb_05.**png**_

**Comment by gldtn** [comment]
Thanks.. I just wanted to rule bootstrap3 out.

Seems like it's throwing a "503 Service Unavailable", so I'll it's most likely something on my server.

Thanks once again for the prompt reply!

**Comment by polyzen** [comment]
@gldtn, please close this if it is resolved.

**Comment by gldtn** [comment]
This was not related to bootstrap 3. Issued closed!
