### ISSUE TITLE
Allow accordion to start collapsed

### ISSUE THREAD

**Issue by reissmann** [LotarProject/dokuwiki-plugin-bootswrapper#46]
It would be a nice feature to allow the "accordion" to start in all-collapsed mode, like it is possible with the "collapse". It's quite hard to collapse the panels using javascript as the id is autogenerated.

In theory this would mean to leave the css class "in" out:

```
<div id="gd389dhnn_drcivmm5c" class="panel-collapse collapse in" role="tabpanel">
```

I thought to find the relevant code in syntax/panel.php or syntax/accordion.php, but I wasn't right :)

**Comment by LotarProject** [comment]
Hi @reissmann,
i have added a new attribute ``collapsed`` to enable/disable this feature:

```
<accordion collapsed="true"> ... </accordion>
```

Thanks for your idea!

Best regards,
Joseph

**Comment by reissmann** [comment]
Awesome! Tested and works like expected. Thank you for implementing this!

**Comment by SchulSkripts** [comment]
Hi,
that attribute doesn't work on my wiki. It just shows the _text_  <accordion collapsed="true">. I think it is not correctly parsed.

Best regards,
geo

**Comment by LotarProject** [comment]
@SchulSkripts , this problem sill there ?
