### ISSUE TITLE
Interwiki link to a tab

### ISSUE THREAD

**Issue by reissmann** [LotarProject/dokuwiki-plugin-bootswrapper#47]
When using the "Tab Pane" (Nav tabs), it would be great to be able to link to a specific tab.

I.e., when there are 3 tabs on a wiki page, I would like to be able to link to the page but immediately open tab 2 or 3. This is not possible by just adding the anchor id to the link, as this doesn't automatically calls the javascript needed to switch tabs.

Is there a simple solution for this?

**Comment by LotarProject** [comment]
Hi @reissmann,
i have implemented in develop branch this feature. This is a sample page to test:

```
[[#tab-foo|Test Foo]] -- [[#tab-bar|Test Bar]]

----

<tabs>
  * [[#tab-foo|Foo]]
  * [[#tab-bar|Bar]]

<pane id="tab-foo">
=== Foo ===
Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</pane>

<pane id="tab-bar">
=== Bar ===
Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</pane>

</tabs>
```

**Comment by reissmann** [comment]
Exactly what I needed. Thank you!

There is one minor issue. When you click on a link like the following, the correct tab is shown and location.hash is added to the url in the address bar.

    [[#tab-foo|Foo]]

However, if you click on a tab, the URL stays the same, preventing the link from working a second time.

In your example:
* Load the page
* Click on the link [[#tab-bar|Test Bar]]
* Click on the Foo-Tab
* Click on the link again (will not work)

This is, however, a very uncommon usecase, as most of the time one will link from one page to another.

**Comment by LotarProject** [comment]
Hi, this is a normal behavior of Bootstrap to prevent a page scrolling when click on tab link.
