### ISSUE TITLE
Editor menu

### ISSUE THREAD

**Issue by Valiantiam** [LotarProject/dokuwiki-plugin-bootswrapper#56]
Is it possible to get a menu on the editor for the different syntax options similar to how wrapper does it? this is incredibly useful for those that work on my wiki but do not have time to look up specific syntax each time they need to use it.

**Comment by LotarProject** [comment]
Hi @Valiantiam i have added this feature in latest release (v2017-03-21). See the Bootstrap icon in editor mode ;)

At your disposal,
Josepht

**Comment by Valiantiam** [comment]
I made the following changes that fixed it:

```
if(!defined('DOKU_INC')) define('DOKU_INC', dirname(__FILE__).'/../../../../');
#define('DOKU_INC', '/var/www/htdocs/dokuwiki/');
define('DOKU_MEDIAMANAGER', 1); // needed to get proper CSS/JS
```

**Comment by LotarProject** [comment]
Sorry :P
I have fixed this behavior in last commit.

Thanks!!!!

At your disposal,
Joseph!

**Comment by Valiantiam** [comment]
Awesome! Thanks for all the efforts.
