### ISSUE TITLE
Menu Button Dropdowns Don't Work (Profile/Options)

### ISSUE THREAD

**Issue by IanSmithers** [LotarProject/dokuwiki-plugin-bootswrapper#57]
The small menu buttons (spanner icon, and a person icon) on the top menu bar, don't appear to drop down. This is a recent update to the latest Elenor of Tsort hotfix.

If I edit the CSS styles via the inspector, I can see that the list is fully populated with icons/text/links which all work. But the actual click event to display that <ul> element doesn't appear to do anything.

Any help appreciated, really frustrating issue this one.

**Comment by IanSmithers** [comment]
Apologies, I just noticed that the option for using the 'default' bootswrapper template was ticked, and specifically says not to use that if there is a Bootstrap template installed and active (which there was).

Disabling this option resolved the issue. Thanks for a great plugin.

**Comment by polyzen** [comment]
@IanSmithers, glad you got it resolved. :) Please close this issue when you get a chance.
