### ISSUE TITLE
Modal(s) not working proper in navbar

### ISSUE THREAD

**Issue by siggi11** [LotarProject/dokuwiki-plugin-bootswrapper#59]
i wanna use the Modal feature in the Navbar. The Navbar is for ALL sites on the top with serval buttons.
The buttons sould show alway the same..,  independent for the current site...

![button with modal](https://cloud.githubusercontent.com/assets/7629603/20136482/45e0e1a8-a675-11e6-968a-bdcac696a8ff.png)

the frame opens but the screen is blocked completely. You have to colse the site.. :-(

![image](https://cloud.githubusercontent.com/assets/7629603/20136538/afa622b0-a675-11e6-86a3-178197b96964.png)

any suggestion for making "modal" in Navbar woking fine?
- is't possible to transfer the "<modal...> - code to another "neutral" site (not the "navbar" site)?
- can the "navbar"-site learn ignor <modal>-Code as Topic point?  

Kindest regards

**Comment by LotarProject** [comment]
Hi @siggi11, can you send a snippet of DokuWiki page (navbar and modal) ?

Thanks,
Joseph

**Comment by siggi11** [comment]
Hi,
the side structure is:
`.../MyWiki/
        |------- .... 
        |-------testBootstrap3
                          |----------- navbar
                          |----------- test1
                          |----------- test2
                          |---- .......    `  

i use the LoadSkin Template Manager changing the template per page/namespace for Test Bootstrap3..  

Code form side navbar:
`  * {{icon>calendar?24&pack=fa}} /*Termine*/
    * <btn type="success" block="true" modal="zugesagt">Zugesagte Termine</btn> 
    * <btn type="warning" block="true" modal="anfragen">Anfragen</btn>
    * <btn type="info" block="true" modal="abstimmung">Abstimmung Übersicht</btn>
  * {{icon>music?24&pack=fa}}
    * <btn type="default" block="true" modal="musik">Player & Download</btn> 
    * <btn type="default" block="true" modal="noten">Notenbibliothek</btn>
    * <btn type="default" block="true" modal="presse">Presse</btn>
  * {{icon>envelope-o?24&pack=fa}}  /*Kontakte*/
    * [[http://www.octophones.de/iaddressbook201/?u=octo&p=octo|Octo-Adressbuch]]
    * [[:bankverbindung|Bankverbindung]] 
    * {{popup>e-Mail?[startsite:mail_adressen_octophones]?300px/730px}}
  * {{icon>picture-o?24&pack=fa}}  /*Gallerie & Sonstiges*/
    * {{popup>Galerie?[startsite:gallery:]?630px/670px}}
    * [[playground:test|Im Sandkasten üben]]
  * [[discussion:ich_kann_heute_nicht|{{:anderes:icons:ich_kann_heute_nicht.png?35|Ich kann heute nicht}}]]
  * [[discussion:allgemeine_disskussion|{{:anderes:icons:write.png?35|Allgemeine Diskussion}}]]
  * [[startsite:abstimmung|{{:anderes:icons:diskussion2.jpg?35|über Anfragen abstimmen...}}]]

<modal id="anfragen" fade="false" size="sm" remote=":startsite:termine:anfragen"></modal>
<modal id="zugesagt" fade="false" size="sm" remote=":startsite:termine:zugesagt"></modal>
<modal id="abstimmung" fade="false" size="sm" remote=":startsite:abstimmung"></modal> 
<modal id="musik" fade="false" size="sm" remote=":musik"></modal>
<modal id="noten" fade="false" size="sm" remote=":noten"></modal>
<modal id="presse" fade="false" size="sm" remote="startsite:presse:2010_otterstadt"></modal>
~~NOCACHE~~`

**Comment by siggi11** [comment]
again: Code froam side navbar:
![grafik](https://cloud.githubusercontent.com/assets/7629603/20859305/3114a45a-b95b-11e6-9c41-9ba72c6d2526.png)

**Comment by siggi11** [comment]
-.-

**Comment by LotarProject** [comment]
Hi @siggi11,
i have tested your code in my environment and i suggest to use ``backdrop="false"`` attribute on every modal element.

**Comment by siggi11** [comment]
Thanks for testing.., but "backdrop=..." also doesn't work. The color changed!,  but not the behavior.
The page is still completely blocked. You have to relaod the page.


![image](https://cloud.githubusercontent.com/assets/7629603/21042713/8bb8cc14-bdf3-11e6-953f-7c5f3ea3cd99.png)

**Comment by LotarProject** [comment]
The page is blocked because this is a default behavior of modal element. To use a ``backdrop`` option i suggest to move the modal elements into a hook (eg. ``pageheader``, ``sidebar``). Actually ``remote`` modal don't have a close button but i'm writing a new patch to include the title and close button.

**Comment by siggi11** [comment]
Thank you!

**Comment by siggi11** [comment]
by the way... the "remote=" - parameter always create a dialog wihtout close button.  But 
i found a pretty nice workaround to show the modal dialog with a close button.
Instead "remote="  i use die include-plugin witch include another wiki page into the current one...

former /not working line:
<modal id="hmhm" size="sm" backdrop="false" remote="namespace:id"></modal>

workaround:
<modal id="hmhm" size="sm" backdrop="false">{{page>[id]&[flags]}}</modal>

worksfine for me at the moment.

BTW 2nd:    Where i can change the "sm" default with?

**Comment by siggi11** [comment]
upps. sorry. the code lines are lost in space...

former:
`<modal id="1" fade="false" size="sm" backdrop="false" remote="[pageId]"></modal>`

workaround:
`<modal id="1" fade="false" size="sm" backdrop="false">{{page>[pageId]&[flags]}}</modal>`
