### ISSUE TITLE
problem nav with include plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-plugin-bootswrapper#6]
Hi,

when using the "include plugin" inside of a nav block the tab function gets corrupted. 
Example:
```
<nav>
  * [[#tab-foo|Foo]]
  * [[#tab-bar|Bar]]
 
<pane id="tab-foo">
=== Foo ===
Lorem ipsum dolor sit amet ...
</pane>
 
<pane id="tab-bar">
{{page>wiki:start}}
</pane>
 
</nav>
```
The included page "wiki:start" not only appears in the "tab-bar", but also in each other tab.

Best regards
Juergen

**Comment by LotarProject** [comment]
Hi! To solve this problem i use `inline` flag. From the "plugin:include" documentation:

*Don't close/open sections when including a page. This flag should be used when the include syntax is used inside other syntax elements like lists or tables or inside other plugin syntax.*

Thank you to reporting this issue, I'm going to add in plugin documentation this "workaround".

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, that's the solution

Best regards
Juergen
