### ISSUE TITLE
panel won't collaps in accordion

### ISSUE THREAD

**Issue by berot3** [LotarProject/dokuwiki-plugin-bootswrapper#61]
for example:

```
<accordion>
<panel type="default" title="Panel title" no-body="true">
^ # ^ First Name ^ Last Name ^ Username ^
^ 1 | Mark       | Otto	     | @mdo     |
^ 2 | Jacob      | Thornton  | @fat     |
^ 3 | Larry      | the Bird  | @twitter |
</panel>
<panel title="Collapsible Group Item #2"> [...] </panel>
<panel title="Collapsible Group Item #3"> [...] </panel>
</accordion>
```

looks like this:
![image](https://cloud.githubusercontent.com/assets/52616/20755271/a34c7cae-b70e-11e6-836e-d80dff9e20e0.png)

**Comment by LotarProject** [comment]
Hi, i have investigated your issue and the problem is ``no-body`` attribute which is in conflict with Bootstrap Accordion plugin.

At your disposal,
Joseph

**Comment by dolandemort** [comment]
I have been having this same issue: Panels that use the `no-body` attribute will not collapse when inside of an accordion.

I am a little confused upon reading your reply. It seems to me that a feature (accordion) of one of the parts of you Bootstrap Wrapper does not cooperate well with another feature of Bootstrap Wrapper (panel). If I have understood the situation correctly, is it not something you would want to address?
