### ISSUE TITLE
NAV actvation-level does not change

### ISSUE THREAD

**Issue by NikolausMB** [LotarProject/dokuwiki-plugin-bootswrapper#62]
I use "Navs" of your great plugin to show a menue at the sidebar. My Template is "bootstrap3".
My attributes: nav type="pills" stacked="true"

Sometimes an item is highlighted (li class="level1 active"), but the corresponding page is not active. 
This appearance will remain the same, even if another entry is selected. I can not change it.

![nav](https://cloud.githubusercontent.com/assets/1101285/21006449/44456e88-bd39-11e6-9574-28831e1ebd94.png)

Sometimes the effect does not occur at all, all entrys look the same (li class="level1").

Unfortunately, I do not know how to trigger it.

**Comment by LotarProject** [comment]
Hi @NikolausMB,
i suggest to add ``~~NOCACHE~~`` macro for synchronize the highlight/active effect only for current page.

**Comment by NikolausMB** [comment]
That's it, thankyou!
All works fine.
