### ISSUE TITLE
Syntax Errors on Homepage 

### ISSUE THREAD

**Issue by TheZachh** [LotarProject/dokuwiki-plugin-bootswrapper#66]
Hello, 

  Since I updated the Bootwrapper to the latest version as of March 2017 I've got horribly annoying errors on my public facing website.  

  Disabling the wrapper removes the errors but of course renders the site to nothing since I rely on the wrapper. 

  I am using the bootstrap3 template which is up to date. I have removed both bootstrap3 template and bootswrapper plugin and reinstalled them. 

 Issue persists.

**Comment by TheZachh** [comment]
Warning: Missing argument 1 for syntax_plugin_bootswrapper_bootstrap::mergeCoreAttributes(), called in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/button.php on line 73 and defined in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php on line 287

Warning: Missing argument 1 for syntax_plugin_bootswrapper_bootstrap::mergeCoreAttributes(), called in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/button.php on line 73 and defined in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php on line 287

Warning: Missing argument 1 for syntax_plugin_bootswrapper_bootstrap::mergeCoreAttributes(), called in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/button.php on line 73 and defined in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php on line 287

Warning: Missing argument 1 for syntax_plugin_bootswrapper_bootstrap::mergeCoreAttributes(), called in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/button.php on line 73 and defined in /home/slmagicc/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php on line 287

**Comment by TheZachh** [comment]
I also combed through the code and referenced the lines above but can't determine why it's occurring. Any help would be appreciated, my wiki is useless without this plugin :) thanks!

**Comment by LotarProject** [comment]
Hi @TheZachh,
thanks for reporting this issue. I have fixed this issue in last commit.

At your disposal,
Joseph

**Comment by TheZachh** [comment]
Thank you so much. I knew it had to be something simple, as it was only occurring on pages with buttons. I adjusted the code with your solution and it worked like a charm. Keep up the great work!
