### ISSUE TITLE
Color me purple

### ISSUE THREAD

**Issue by MvErven** [LotarProject/dokuwiki-plugin-bootswrapper#69]
Question: Can we have custom colors for panels, butons, nav's, alerts and so on?
Just like the color attribute at callouts, Or can someone guide me how to achieve this?
Thanks!

**Comment by LotarProject** [comment]
You can extends the standard Bootstrap panels via CSS. I think this is the solution:

Create a new panel class into ``userall.css`` (manually or via [Advanced Plugin](https://www.dokuwiki.org/plugin:advanced))

```.css
.bs-wrapper.panel-purple .panel {
    border-color: #ff00ff;
}
.bs-wrapper.panel-purple .panel-default > .panel-heading {
    background: #ff00ff; 
    color: #ffffff;
    border-color: #ff00ff;
}
```

Now use wrapper + panel syntax:
```
<WRAPPER class="panel-purple">
<panel type="default">
[...]
</panel>
</WRAPPER>
```

At your disposal,
Joseph

**Comment by MvErven** [comment]
Thank you for your time. First attempt failed. (Saved userall.css with advanced plugin, purged css but no result) Tomorrow I make a second attempt.  Gracie.
![snapshot3](https://user-images.githubusercontent.com/17900348/31131657-01c8607a-a85b-11e7-9e49-6f1adb22d8f3.png)
![snapshot4](https://user-images.githubusercontent.com/17900348/31131658-01cde5e0-a85b-11e7-93ba-c8dc61671460.png)

**Comment by MvErven** [comment]
Good day Apparently my cache was not completely refreshed. I have the desired result. Thank you!

**Comment by LotarProject** [comment]
👍 

You can purge the DokuWiki cache via URL (http://<dokuwiki>/lib/exe/css.php?purge=true) or via Advanced Plugin (after, purge your browser cache).

I'm plan to extend ``<panel>`` syntax to accept "class" attribute to simplify the job:

```
<panel type="default" class="panel-purple">
[...]
</panel>
```

At your disposal,
Joseph
