### ISSUE TITLE
ProgressBar Debug

### ISSUE THREAD

**Issue by One19wil** [LotarProject/dokuwiki-plugin-bootswrapper#70]
Hello, the progressbar doesn't work. I have edit : 

> syntax/progressbar.php

and now it's work with 2 tags 
`<progress>
<bar value="..." striped="bool" animate="bool"></bar>
</progress>`

so i give you the code
Best regards.

[progressbar.zip](https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/files/1098945/progressbar.zip)

**Comment by MvErven** [comment]
Why? The progress bar works for me without changes.

`<panel type="default" title="test">
Link to image or page
<progress>
<bar value="99" type="warning" striped="true" showvalue="false" animate="true">Never ending story</bar>
</progress>
</panel>`

**Comment by LotarProject** [comment]
@One19wil this problem is still there ?
