### ISSUE TITLE
Carousel - Images not centered

### ISSUE THREAD

**Issue by sceptiq** [LotarProject/dokuwiki-plugin-bootswrapper#72]
Hey, 

i am trying to use the carousel to display a bunch of images. But they are not properly aligned (centered?) they are all aligned left. Even if they have all the same size ...

![screen shot 2017-09-08 at 17 44 01](https://user-images.githubusercontent.com/8125020/30219795-76eb07c4-94bd-11e7-9541-b068fc5c9816.png)

some options to manipulate the carousel like the size would be nice too :) 

what do i have to do to get centered images in my carousel? 

thx !

**Comment by MvErven** [comment]
Best thing I can imagine is to have the image centered in a larger canvas size. In other words my canvas size is the same size (as the picture) on both sides of the image.

**Comment by LotarProject** [comment]
Hi, i have added a fix in develop branch that solve this problem.
