### ISSUE TITLE
Fixed height for panels

### ISSUE THREAD

**Issue by MvErven** [LotarProject/dokuwiki-plugin-bootswrapper#73]
Can we give a panel a fixed height? For instance, I created 2 panels in one row. However those panels are slightly different in size. I would like to have them both the same height. How to?

**Comment by LotarProject** [comment]
Hi,
please you can send a snippet of the code or a screenshot of your panels ?

Generally the size of this containers (panels, tabs, etc) follow the content.

At your disposal,
Joseph

**Comment by MvErven** [comment]
Thank you for your time. Appoligies for my previous 'urge to reply'
I have attached 2 snapshots and also 2 txt files.    

Sincerly, Michiel.
![snapshot2](https://user-images.githubusercontent.com/17900348/31129931-4e2f4bb8-a856-11e7-8423-1f35ed7c248b.png)
[mijnimport-snapshot2.txt](https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/files/1352588/mijnimport-snapshot2.txt)
![snapshot1](https://user-images.githubusercontent.com/17900348/31129932-4e30dac8-a856-11e7-967f-8025ced9a64d.png)
[regeling-snapshot1.txt](https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/files/1352587/regeling-snapshot1.txt)

**Comment by MvErven** [comment]
Well, I've done it with a work-around.

Using HTML and a form: 
 'div style="height:540px;overflow:auto;"'

Missing -form- objects;  my wiki gets mixed with HTML and Bootswrapper. But it's ok for now.
