### ISSUE TITLE
Better compatibility between bootswrapper and other templates?

### ISSUE THREAD

**Issue by GJRobert** [LotarProject/dokuwiki-plugin-bootswrapper#74]
(A repost of [[How?] Better compatibility between bootswrapper and other templates? - DokuWiki User Forum](https://forum.dokuwiki.org/thread/15166 "[How?] Better compatibility between bootswrapper and other templates? - DokuWiki User Forum"))

Below is a normal screenshot of writr template:
![normal writr look](http://ciangbrides.myds.me/pictshare/1000x1000/dtf00uhwuj.png)

In order to use bootswrapper plugin and make Bootstrap widgets work along with other non-bootstrap3 templates, I have checked `plugin»bootswrapper»loadBootstrap` as it told "Load the Bootstrap vanilla CSS. Disable it if you have installed a Bootstrap based template."

But Bootstrap vanilla CSS seems to break templates other than bootstrap3 in many ways (font-size, font-family, font-color etc.) (screenshot below)
![broken look of writr](http://ciangbrides.myds.me/pictshare/1000x1000/ocpuyufuhc.png)

Is there a better way to keep bootswrapper goodies work while not messing the proper look of those beautiful templates?

**Comment by LotarProject** [comment]
Hi @GJRobert,
this plugin work only with Bootstrap compatible themes. You can enable `loadBootstrap` flag (in Configuration Settings) but i think this causes a visual artifact (or malfuntions) if your template don't support Bootstrap classes.

**Comment by GJRobert** [comment]
Hi Lotar,
Thank you so much for instruction! Now I understand Bootstrap better...
