### ISSUE TITLE
Why get this feeling?

### ISSUE THREAD

**Issue by MvErven** [LotarProject/dokuwiki-plugin-bootswrapper#76]
Why do I get the feeling my previous questions gets ignored? While other newer 'issues' are answered? Just becaus I'm no programmer or something?

**Comment by LotarProject** [comment]
I'm sorry I have not responded recently, but besides devoting time to work I have many priority projects and being released on GitHub.
Generally I give priority to critical issues such as errors or incompatibilities (other plugins, webservers, PHP, etc).

At your disposal,
Joseph
