### ISSUE TITLE
Implementing the progress component

### ISSUE THREAD

**Issue by HavocKKS** [LotarProject/dokuwiki-plugin-bootswrapper#8]
Hello im working on an implementation of the progress component.

Features implemented :
- Displaying Label
- Showing value in label. Ex : 95% My Label
- Contextual alternatives
- Striped bars
- Animation
- Bar Stacking

Here is the wiki syntax that i propose (just a prototype of course):
```xml
<progress>
<bar value="20" showvalue="1" animate="1" striped="1" type="warning">My Label</bar>
<bar value="10" type="primary"></bar>
</progress>

<progress>
<bar value="90" showvalue="0" type="primary"></bar>
</progress>
```

This what i've got so far...
![progressbars](https://cloud.githubusercontent.com/assets/12526678/8904530/82049090-3460-11e5-9df4-8b2932e45eb2.png)

**Comment by LotarProject** [comment]
Thank you to have implemented this component! I have updated my documentation with some examples (http://lotar.altervista.org/dokuwiki/wiki/plugin/bootswrapper/progress-bar)

**Comment by HavocKKS** [comment]
@LotarProject Awesome ^^
