### ISSUE TITLE
Navs get two symbols for dropdown in :namespace:navbar

### ISSUE THREAD

**Issue by sarrangril** [LotarProject/dokuwiki-plugin-bootswrapper#82]
I use dropdown-navs in namespace navbars for navigation and get two of the triangles signaling a dropdown-menu in the navbar, but not in the wiki page for the navbar (see screenshot). This does not effect the dropdown in any way, it's working fine.

```
<nav type="pills">
  * Links
    * [[test|Link 1]]
    * [[test2|Link 2]]
  * About
    * [[me|Me]]
    * [[you|You]]
</nav>
```

![screenshot](https://user-images.githubusercontent.com/5368095/36342723-a8bd5738-1402-11e8-8bca-f6632af99cbe.jpg)

Using plugin version 2017-04-07, wiki version 2017-02-19e

**Comment by LotarProject** [comment]
Hi,
Is not necessary to use the ``<nav>`` tag in the ``:navbar`` page because is a special page for Bootsrap3 template and any list are automatically converted into a navbar.

At your disposal,
Joseph
