### ISSUE TITLE
Accordion usage...

### ISSUE THREAD

**Issue by jcamp** [LotarProject/dokuwiki-plugin-bootswrapper#96]
Hi

Love all the bootstrap stuff - nice.

You have an **accordion** option. Added the accordion but not sure how this links up with the content for accordion - id's or ? Do you have some documentation for the accordion anywhere?

Cheers

**Comment by MvErven** [comment]
Hello jcamp. I'll give you an example of one of my pages. (it's worth a try)
Accordion with panels. (Panels can have attributes)

Maybe this will help.
[accordion.txt](https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/files/2248938/accordion.txt)

Good luck.

**Comment by jcamp** [comment]
Nice one! Thanks...
