### ISSUE TITLE
Callout with Icon Gets Pushed By TOC

### ISSUE THREAD

**Issue by ERTurner** [LotarProject/dokuwiki-plugin-bootswrapper#99]
We use callouts with icons, but when they are placed at the top of the page, the TOC will push down the content of the callout. This seems to be due to the row/column div use within the icon callouts. I haven't been able to figure out a fix for this.

![capture](https://user-images.githubusercontent.com/16724278/47105109-df670c80-d1f7-11e8-8fc5-26e9899e1b4a.JPG)

**Comment by ERTurner** [comment]
Oh wow, I learned all about floats today. Here's a breakdown of what is causing this:

`<callout icon="true" title="anything"></callout>` contains a `div.row` with 2 `div.col`. The second `div.col` has a float, which needs to be removed so that the content wraps when the TOC is open. The `div.row:after` has a `clear:both`, which is causing the callout container to grow with the TOC.

Here's the CSS I used to fix this:
`div.bs-wrap.bs-callout .row div:nth-child(2) {`
	`float: none;`
`}`

`div.bs-wrap.bs-callout .row:after {`
	`clear: none;`
`}`

I am not a front-end developer, so I'm sure there is a better way to implement this fix that is beyond my current knowledge of CSS.

**Comment by ERTurner** [comment]
> I had some success by adding the following to my 'userstyles.css':
> 
> ```
> div.bs-wrap.bs-callout {
>   overflow: hidden;
> }
> ```

Oh wow, this is much better than my fix. Thank you so much for sharing!

**Comment by Miro-Collas** [comment]
Thanks for sharing! I had this exact issue, which I had reported over on dokuwiki-template-bootstrap3 but that got no reply.

**Comment by LotarProject** [comment]
Fixed this issue with @Miro-Collas patch on develop branch
